### ISSUE TITLE
T'estic vigilant! ;D

### ISSUE THREAD

**Issue by gitatmanu** [gatrenat/introprg#1]
Bona sort amb el temari.

**Comment by gatrenat** [comment]
Gràcies
Gaudeix de l'estiu!
*---*

*Moisès GómezINS Joan d'Àustria*
[image: IES Joan d'Àustria] <https://agora.xtec.cat/insjoandaustria/>


Missatge de Manel ***@***.***> del dia dv., 30 de jul. 2021 a
les 16:35:
